# Use the official Node.js image as the base image
FROM node:18-alpine

# Set the working directory
WORKDIR /app

# Copy the package.json and package-lock.json files
COPY package*.json ./
COPY eslint.config.js ./
COPY vite.config.js ./

# Install dependencies
RUN npm install

# Copy the rest of the application
COPY . .

# Expose the port the app runs on (default Vite port is 5173)
EXPOSE 5173

# Start the development server
CMD ["npm", "run", "dev"]