# Use an official Python runtime as a parent image
FROM python:3.10-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1 \
    # Prevents Python from writing pyc files to disc (equivalent to python -B option)
    PYTHONUNBUFFERED 1 \
    # Prevents Python from buffering stdout and stderr (equivalent to python -u option)
    DEBIAN_FRONTEND=noninteractive \
    # Prevents apt from showing prompts
    TZ=UTC

# Set the working directory in the container
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the current directory contents into the container
COPY . .

RUN chmod +x script.sh

# Expose the port the app runs on
EXPOSE 8000

# Define the command to run the application
CMD [ "sh", "script.sh" ]
